### ISSUE TITLE
Long run caused rate become very slow

### ISSUE THREAD

**Issue by k79e** [nmap/ncrack#107]
dump here https://github.com/nmap/ncrack/issues/107#issuecomment-812634787 (win)

I captured some information.

When slow
#0  0x00007fc4e7c137b7 in epoll_wait (epfd=6, events=0x55ebc0091b60,
    maxevents=2460, timeout=500) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1  0x000055ebb9cc0a4a in ?? ()
#2  0x000055ebb9cbc152 in ?? ()
#3  0x000055ebb9c94058 in ?? ()
#4  0x000055ebb9c8f01f in ?? ()
#5  0x00007fc4e7b3e09b in __libc_start_main (main=0x55ebb9c8efe0, argc=18,
    argv=0x7fff65080948, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7fff65080938)
    at ../csu/libc-start.c:308
#6  0x000055ebb9c8f2aa in ?? ()

---------------------
#0  0x00007fc4e7c137b7 in epoll_wait (epfd=6, events=0x55ebc0091b60,
    maxevents=2460, timeout=500) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
        resultvar = 18446744073709551612
        sc_ret = <optimized out>
#1  0x000055ebb9cc0a4a in ?? ()
No symbol table info available.
#2  0x000055ebb9cbc152 in ?? ()
No symbol table info available.
#3  0x000055ebb9c94058 in ?? ()
No symbol table info available.
#4  0x000055ebb9c8f01f in ?? ()
No symbol table info available.
#5  0x00007fc4e7b3e09b in __libc_start_main (main=0x55ebb9c8efe0, argc=18,
    argv=0x7fff65080948, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7fff65080938)
    at ../csu/libc-start.c:308
        self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 577217003279914274,
                94470922629760, 140734888413504, 0, 0, 6641426551534556450,
                6655215468075717922}, mask_was_saved = 0}}, priv = {pad = {
              0x0, 0x0, 0x7fff650809e0, 0x7fc4e83ab190}, data = {prev = 0x0,
              cleanup = 0x0, canceltype = 1695025632}}}
        not_first_call = <optimized out>
#6  0x000055ebb9c8f2aa in ?? ()
No symbol table info available.

========================================================
Not slow
#0  0x0000557e1ac3d7b6 in ?? ()
#1  0x0000557e1ac3ddca in ?? ()
#2  0x0000557e1ac337aa in ?? ()
#3  0x0000557e1ac3353c in ?? ()
#4  0x0000557e1ac07f65 in ?? ()
#5  0x0000557e1abf1e97 in ?? ()
#6  0x0000557e1ac1fb9e in ?? ()
#7  0x0000557e1ac1d689 in ?? ()
#8  0x0000557e1ac21aec in ?? ()
#9  0x0000557e1ac1d152 in ?? ()
#10 0x0000557e1abf5058 in ?? ()
#11 0x0000557e1abf001f in ?? ()
#12 0x00007f7e08cc109b in __libc_start_main (main=0x557e1abeffe0, argc=18,
    argv=0x7fff67bd7288, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7fff67bd7278)
    at ../csu/libc-start.c:308
#13 0x0000557e1abf02aa in ?? ()

------------------
#0  0x0000557e1ac3d7b6 in ?? ()
No symbol table info available.
#1  0x0000557e1ac3ddca in ?? ()
No symbol table info available.
#2  0x0000557e1ac337aa in ?? ()
No symbol table info available.
#3  0x0000557e1ac3353c in ?? ()
No symbol table info available.
#4  0x0000557e1ac07f65 in ?? ()
No symbol table info available.
#5  0x0000557e1abf1e97 in ?? ()
No symbol table info available.
#6  0x0000557e1ac1fb9e in ?? ()
No symbol table info available.
#7  0x0000557e1ac1d689 in ?? ()
No symbol table info available.
#8  0x0000557e1ac21aec in ?? ()
No symbol table info available.
#9  0x0000557e1ac1d152 in ?? ()
No symbol table info available.
#10 0x0000557e1abf5058 in ?? ()
No symbol table info available.
#11 0x0000557e1abf001f in ?? ()
No symbol table info available.
#12 0x00007f7e08cc109b in __libc_start_main (main=0x557e1abeffe0, argc=18, argv=0x7fff67bd7288, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff67bd7278) at ../csu/libc-start.c:308
        self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 8541413375171386238, 94000102965888, 140734933856896, 0, 0, 2561361574033644414, 2488544617979075454}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x7fff67bd7320, 0x7f7e0952e190}, data = {prev = 0x0, cleanup = 0x0, canceltype = 1740469024}}}
        not_first_call = <optimized out>
#13 0x0000557e1abf02aa in ?? ()
No symbol table info available.

Looks there is a epoch_wait in thread0? When rate dropped down to a very slow one.

**Comment by k79e** [comment]
I generated a minidump when it stucks . Hope it can capture some useful information.
[ncrack.7z.zip](https://github.com/nmap/ncrack/files/6250688/ncrack.7z.zip)
