### ISSUE TITLE
ncrack segmentation fault error specific to SSH service brute force

### ISSUE THREAD

**Issue by triznut** [nmap/ncrack#38]
I receive the following error message when trying to brute force SSH services:

ncrack -v --user root -P /usr/share/wordlists/rockyou-custom.txt 10.xx.xx.xx:22

Starting Ncrack 0.6 ( http://ncrack.org ) at 2018-03-27 10:40 MDT

Segmentation fault

Dmesg Log:

[  300.771692] ncrack[2222]: segfault at 8 ip 00007f8ac720b849 sp 00007ffd7b8e7140 error 4 in libcrypto.so.1.1[7f8ac714a000+262000]

**Comment by ithilgore** [comment]
Can you retry with the latest version of Ncrack (0.7 on github) compiled against OpenSSL 1.1?

**Comment by denevin** [comment]
@ithilgore Problem still exists in Ncrack 0.7 compiled against OpenSSL 1.1

**Comment by OdimFR** [comment]
I found a solution, try to save your file without .txt extension that's work for me, have a good day 👍

**Comment by doomguy** [comment]
Had the same issue today wit ncrack 0.5. (This is the version found in the fedora repos.)

I found that the wordlist needs to have a blank line at the end in order not to segfault.

**Comment by doomguy** [comment]
Just compiled ncrack 0.7 with openssl 1.1.0i-fips. Now I can't brute any ssh service anymore.

I tried 4 test cases in total:
- wordlist without extension and without trailing blank line
- wordlist without extension and with trailing blank line
- wordlist with extension and without trailing blank line
- wordlist with extension and with trailing blank line

I attached the dmesg log to this message.
[ncrack_segfault.txt](https://github.com/nmap/ncrack/files/2595948/ncrack_segfault.txt)

**Comment by same7ammar** [comment]
> I found a solution, try to save your file without .txt extension that's work for me, have a good day 👍

i tired to rename file and extension but still facing same issue .

root@pen:~# ncrack -v -T 5 --user admin -P wordlist.txt 192.168.8.110:22

Starting Ncrack 0.6 ( http://ncrack.org ) at 2018-11-25 04:29 EST

Segmentation fault

**Comment by Velby** [comment]
ping, same issue here

**Comment by ianatha** [comment]
I was able to reproduce this with master at f8c52a5e0d59f3a72a7374c3d35fcc148f0f2a15.

```
root@b8e2dabd2670:/# openssl version
OpenSSL 1.1.1  11 Sep 2018

root@b8e2dabd2670:/# ncrack -v --user root -P /root/password.txt 10.17.4.34:22

Starting Ncrack 0.7 ( http://ncrack.org ) at 2019-06-13 01:02 UTC

Segmentation fault
```

Compiled it with `-O0 -g3`, and ran it through gdb (some lines omitted):

```
Program received signal SIGSEGV, Segmentation fault.

#0  0x00007f8deb29a999 in BN_num_bits () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#1  0x00005596f862db5a in dh_pub_is_valid (dh=dh@entry=0x5596f953f750, dh_pub=0x0) at dh.c:221
#2  0x00005596f862ddd1 in dh_gen_key (dh=0x5596f953f750, need=<optimized out>) at dh.c:275
#3  0x00005596f8612610 in ncrackssh_input_kex_dh_gex_group (nstate=0x5596f95468b0) at kexgexc.c:131
#4  0x00005596f85ed5f6 in ncrack_ssh(npool*, Connection*) ()
#5  0x00005596f85d6eb7 in ncrack_read_handler(npool*, nevent*, void*) ()
#6  0x00005596f860581e in event_dispatch_and_delete (nsp=nsp@entry=0x5596f9519ce0, 
    nse=nse@entry=0x5596f9546760, notify=notify@entry=1) at nsock_event.c:373
#7  0x00005596f8602ddd in process_event (nsp=nsp@entry=0x5596f9519ce0, 
    evlist=evlist@entry=0x5596f9519d10, nse=nse@entry=0x5596f9546760, ev=ev@entry=1)
    at nsock_core.c:1058
#8  0x00005596f8603199 in process_iod_events (nsp=nsp@entry=0x5596f9519ce0, 
    nsi=nsi@entry=0x5596f9546590, ev=1) at nsock_core.c:1123
#9  0x00005596f86077dc in iterate_through_event_lists (evcount=1, nsp=0x5596f9519ce0)
    at engine_epoll.c:329
#10 epoll_loop (nsp=0x5596f9519ce0, msec_timeout=<optimized out>) at engine_epoll.c:312
#11 0x00005596f8602c52 in nsock_engine_loop (msec_timeout=2986, nsp=0x5596f9519ce0)
    at nsock_internal.h:431
#12 nsock_loop (nsp=0x5596f9519ce0, msec_timeout=3000) at nsock_core.c:926
#13 0x00005596f85da048 in ncrack_main(int, char**) ()
#14 0x00005596f85d50cf in main ()
```

**Comment by ianatha** [comment]
From valgrind: ```root@eef6412fc1ed:~/ncrack# valgrind ./ncrack  -v --user root -P /root/password.txt 10.17.4.34:22
==64== Memcheck, a memory error detector
==64== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==64== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==64== Command: ./ncrack -v --user root -P /root/password.txt 10.17.4.34:22
==64== 
Warning: File ./ncrack-services exists, but Ncrack is using /usr/local/share/ncrack/ncrack-services for security and consistency reasons. Set NCRACKDIR=. to give priority to files in your local directory (may affect the other data files too).

Starting Ncrack 0.7 ( http://ncrack.org ) at 2019-06-13 01:16 UTC

==64== Invalid read of size 4
==64==    at 0x4995999: BN_num_bits (in /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)
==64==    by 0x16BB59: dh_pub_is_valid (dh.c:221)
==64==    by 0x16BDD0: dh_gen_key (dh.c:276)
==64==    by 0x15060F: ncrackssh_input_kex_dh_gex_group (kexgexc.c:131)
==64==    by 0x12B5F5: ncrack_ssh(npool*, Connection*) (in /root/ncrack/ncrack)
==64==    by 0x114EB6: ncrack_read_handler(npool*, nevent*, void*) (in /root/ncrack/ncrack)
==64==    by 0x14381D: event_dispatch_and_delete (nsock_event.c:373)
==64==    by 0x141198: process_iod_events (nsock_core.c:1123)
==64==    by 0x1457DB: iterate_through_event_lists (engine_epoll.c:345)
==64==    by 0x1457DB: epoll_loop (engine_epoll.c:312)
==64==    by 0x140C51: nsock_engine_loop (nsock_internal.h:431)
==64==    by 0x140C51: nsock_loop (nsock_core.c:926)
==64==    by 0x118047: ncrack_main(int, char**) (in /root/ncrack/ncrack)
==64==    by 0x1130CE: main (in /root/ncrack/ncrack)
==64==  Address 0x8 is not stack'd, malloc'd or (recently) free'd
==64== 
==64== 
==64== Process terminating with default action of signal 11 (SIGSEGV)
==64==  Access not within mapped region at address 0x8
==64==    at 0x4995999: BN_num_bits (in /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)
==64==    by 0x16BB59: dh_pub_is_valid (dh.c:221)
==64==    by 0x16BDD0: dh_gen_key (dh.c:276)
==64==    by 0x15060F: ncrackssh_input_kex_dh_gex_group (kexgexc.c:131)
==64==    by 0x12B5F5: ncrack_ssh(npool*, Connection*) (in /root/ncrack/ncrack)
==64==    by 0x114EB6: ncrack_read_handler(npool*, nevent*, void*) (in /root/ncrack/ncrack)
==64==    by 0x14381D: event_dispatch_and_delete (nsock_event.c:373)
==64==    by 0x141198: process_iod_events (nsock_core.c:1123)
==64==    by 0x1457DB: iterate_through_event_lists (engine_epoll.c:345)
==64==    by 0x1457DB: epoll_loop (engine_epoll.c:312)
==64==    by 0x140C51: nsock_engine_loop (nsock_internal.h:431)
==64==    by 0x140C51: nsock_loop (nsock_core.c:926)
==64==    by 0x118047: ncrack_main(int, char**) (in /root/ncrack/ncrack)
==64==    by 0x1130CE: main (in /root/ncrack/ncrack)
==64==  If you believe this happened as a result of a stack
==64==  overflow in your program's main thread (unlikely but
==64==  possible), you can try to increase the size of the
==64==  main thread stack using the --main-stacksize= flag.
==64==  The main thread stack size used in this run was 8388608.
==64== Invalid read of size 8
==64==    at 0x50E3B89: check_free (dlerror.c:188)
==64==    by 0x50E3B89: free_key_mem (dlerror.c:218)
==64==    by 0x50E3B89: __dlerror_main_freeres (dlerror.c:236)
==64==    by 0x5068A41: __libc_freeres (in /lib/x86_64-linux-gnu/libc-2.28.so)
==64==    by 0x482D19E: _vgnU_freeres (in /usr/lib/valgrind/vgpreload_core-amd64-linux.so)
==64==  Address 0x511ed08 is 12 bytes after a block of size 12 alloc'd
==64==    at 0x483774F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==64==    by 0x4A51CE8: CRYPTO_zalloc (in /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)
==64==    by 0x4A4DFBD: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)
==64==    by 0x4A2F02B: ERR_get_state (in /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)
==64==    by 0x4A2F188: ERR_clear_error (in /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)
==64==    by 0x4A4D738: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)
==64==    by 0x50D10C6: __pthread_once_slow (pthread_once.c:116)
==64==    by 0x4AB6328: CRYPTO_THREAD_run_once (in /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)
==64==    by 0x4A4DEEB: OPENSSL_init_crypto (in /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)
==64==    by 0x49BB01D: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)
==64==    by 0x4A4D7CF: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)
==64==    by 0x50D10C6: __pthread_once_slow (pthread_once.c:116)
==64== 
==64== 
==64== HEAP SUMMARY:
==64==     in use at exit: 158,806 bytes in 3,794 blocks
==64==   total heap usage: 4,985 allocs, 1,191 frees, 435,943 bytes allocated
==64== 
==64== LEAK SUMMARY:
==64==    definitely lost: 1,088 bytes in 4 blocks
==64==    indirectly lost: 0 bytes in 0 blocks
==64==      possibly lost: 864 bytes in 3 blocks
==64==    still reachable: 156,854 bytes in 3,787 blocks
==64==         suppressed: 0 bytes in 0 blocks
==64== Rerun with --leak-check=full to see details of leaked memory
==64== 
==64== For counts of detected and suppressed errors, rerun with: -v
==64== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
Segmentation fault
```

**Comment by TheConen** [comment]
Is there anything new on this? I'm having the same issue.

**Comment by chanuniva** [comment]
just updating ncrack will resolve the issue(apt-get -y install ncrack). 
ncrack version 0.6 seems all affected.

**Comment by cldrn** [comment]
Hey @ithilgore ,

This bug still persists on ncrack 0.8. As mentioned on this thread, it does not segfault when the password list has an empty line.

**Comment by yoke88** [comment]
still segfault when using password file without extension and a empty line 

ncrack version 0.8
